package com.sda.model;

public enum Gatunek { HORROR, OBYCZAJ, PRZYGODA, SCIFI, ROMANS, POEZJA, HISTORYCZNA, KLASYKA, SATYTA, THRILLER, DRAMAT,
                     BIOGRAFIA, BAJKA, KOMIKS, POZOSTALE }